FROM openjdk:8
EXPOSE 8080
ADD target/billingmicroservice/target/billingmicroservice-0.0.1-SNAPSHOT.jar billingmicroservice/target/billingmicroservice-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar", "/docker-jenkins-integration-sample.jar"]